[project]
name = "pyqt-template"
version = "0.1.0"
description = "A template for Qt applications with QML and Python using a MVC design pattern."
requires-python = ">=3.12.9"
dependencies = [
    "pyclean>=3.1.0",
    "pyside6>=6.9.0",
    "ruff>=0.11.12",
    "tomlkit>=0.13.2",
]

[tool.ruff]
indent-width = 4
line-length = 80

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
